// source: agent-kit.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.agent_kit.AgentTalkRequest', null, global);
goog.exportSymbol('proto.agent_kit.AgentTalkRequest.RequestCase', null, global);
goog.exportSymbol('proto.agent_kit.AgentTalkResponse', null, global);
goog.exportSymbol('proto.agent_kit.AgentTalkResponse.DataCase', null, global);
goog.exportSymbol('proto.agent_kit.AssistantActionRequest', null, global);
goog.exportSymbol('proto.agent_kit.AssistantActionRequest.RequestCase', null, global);
goog.exportSymbol('proto.agent_kit.AssistantActionResponse', null, global);
goog.exportSymbol('proto.agent_kit.AssistantActionResponse.DataCase', null, global);
goog.exportSymbol('proto.agent_kit.AssistantActionResult', null, global);
goog.exportSymbol('proto.agent_kit.ConnectAssistantAction', null, global);
goog.exportSymbol('proto.agent_kit.ExecuteAssistantAction', null, global);
goog.exportSymbol('proto.agent_kit.GetAssistantAction', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.ConnectAssistantAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agent_kit.ConnectAssistantAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.ConnectAssistantAction.displayName = 'proto.agent_kit.ConnectAssistantAction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.GetAssistantAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agent_kit.GetAssistantAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.GetAssistantAction.displayName = 'proto.agent_kit.GetAssistantAction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.ExecuteAssistantAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agent_kit.ExecuteAssistantAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.ExecuteAssistantAction.displayName = 'proto.agent_kit.ExecuteAssistantAction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.AssistantActionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.agent_kit.AssistantActionRequest.oneofGroups_);
};
goog.inherits(proto.agent_kit.AssistantActionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.AssistantActionRequest.displayName = 'proto.agent_kit.AssistantActionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.AssistantActionResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agent_kit.AssistantActionResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.AssistantActionResult.displayName = 'proto.agent_kit.AssistantActionResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.AssistantActionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.agent_kit.AssistantActionResponse.oneofGroups_);
};
goog.inherits(proto.agent_kit.AssistantActionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.AssistantActionResponse.displayName = 'proto.agent_kit.AssistantActionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.AgentTalkRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.agent_kit.AgentTalkRequest.oneofGroups_);
};
goog.inherits(proto.agent_kit.AgentTalkRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.AgentTalkRequest.displayName = 'proto.agent_kit.AgentTalkRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agent_kit.AgentTalkResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.agent_kit.AgentTalkResponse.oneofGroups_);
};
goog.inherits(proto.agent_kit.AgentTalkResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agent_kit.AgentTalkResponse.displayName = 'proto.agent_kit.AgentTalkResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.ConnectAssistantAction.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.ConnectAssistantAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.ConnectAssistantAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.ConnectAssistantAction.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.ConnectAssistantAction}
 */
proto.agent_kit.ConnectAssistantAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.ConnectAssistantAction;
  return proto.agent_kit.ConnectAssistantAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.ConnectAssistantAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.ConnectAssistantAction}
 */
proto.agent_kit.ConnectAssistantAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.ConnectAssistantAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.ConnectAssistantAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.ConnectAssistantAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.ConnectAssistantAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.GetAssistantAction.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.GetAssistantAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.GetAssistantAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.GetAssistantAction.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.GetAssistantAction}
 */
proto.agent_kit.GetAssistantAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.GetAssistantAction;
  return proto.agent_kit.GetAssistantAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.GetAssistantAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.GetAssistantAction}
 */
proto.agent_kit.GetAssistantAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.GetAssistantAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.GetAssistantAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.GetAssistantAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.GetAssistantAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.ExecuteAssistantAction.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.ExecuteAssistantAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.ExecuteAssistantAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.ExecuteAssistantAction.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.ExecuteAssistantAction}
 */
proto.agent_kit.ExecuteAssistantAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.ExecuteAssistantAction;
  return proto.agent_kit.ExecuteAssistantAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.ExecuteAssistantAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.ExecuteAssistantAction}
 */
proto.agent_kit.ExecuteAssistantAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.ExecuteAssistantAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.ExecuteAssistantAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.ExecuteAssistantAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.ExecuteAssistantAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.agent_kit.AssistantActionRequest.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.agent_kit.AssistantActionRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  CONNECT: 1,
  GET: 2,
  EXECUTE: 3
};

/**
 * @return {proto.agent_kit.AssistantActionRequest.RequestCase}
 */
proto.agent_kit.AssistantActionRequest.prototype.getRequestCase = function() {
  return /** @type {proto.agent_kit.AssistantActionRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.agent_kit.AssistantActionRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.AssistantActionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.AssistantActionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.AssistantActionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    connect: (f = msg.getConnect()) && proto.agent_kit.ConnectAssistantAction.toObject(includeInstance, f),
    get: (f = msg.getGet()) && proto.agent_kit.GetAssistantAction.toObject(includeInstance, f),
    execute: (f = msg.getExecute()) && proto.agent_kit.ExecuteAssistantAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.AssistantActionRequest}
 */
proto.agent_kit.AssistantActionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.AssistantActionRequest;
  return proto.agent_kit.AssistantActionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.AssistantActionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.AssistantActionRequest}
 */
proto.agent_kit.AssistantActionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.agent_kit.ConnectAssistantAction;
      reader.readMessage(value,proto.agent_kit.ConnectAssistantAction.deserializeBinaryFromReader);
      msg.setConnect(value);
      break;
    case 2:
      var value = new proto.agent_kit.GetAssistantAction;
      reader.readMessage(value,proto.agent_kit.GetAssistantAction.deserializeBinaryFromReader);
      msg.setGet(value);
      break;
    case 3:
      var value = new proto.agent_kit.ExecuteAssistantAction;
      reader.readMessage(value,proto.agent_kit.ExecuteAssistantAction.deserializeBinaryFromReader);
      msg.setExecute(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.AssistantActionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.AssistantActionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.AssistantActionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnect();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.agent_kit.ConnectAssistantAction.serializeBinaryToWriter
    );
  }
  f = message.getGet();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.agent_kit.GetAssistantAction.serializeBinaryToWriter
    );
  }
  f = message.getExecute();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.agent_kit.ExecuteAssistantAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional ConnectAssistantAction connect = 1;
 * @return {?proto.agent_kit.ConnectAssistantAction}
 */
proto.agent_kit.AssistantActionRequest.prototype.getConnect = function() {
  return /** @type{?proto.agent_kit.ConnectAssistantAction} */ (
    jspb.Message.getWrapperField(this, proto.agent_kit.ConnectAssistantAction, 1));
};


/**
 * @param {?proto.agent_kit.ConnectAssistantAction|undefined} value
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
*/
proto.agent_kit.AssistantActionRequest.prototype.setConnect = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.agent_kit.AssistantActionRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
 */
proto.agent_kit.AssistantActionRequest.prototype.clearConnect = function() {
  return this.setConnect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AssistantActionRequest.prototype.hasConnect = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GetAssistantAction get = 2;
 * @return {?proto.agent_kit.GetAssistantAction}
 */
proto.agent_kit.AssistantActionRequest.prototype.getGet = function() {
  return /** @type{?proto.agent_kit.GetAssistantAction} */ (
    jspb.Message.getWrapperField(this, proto.agent_kit.GetAssistantAction, 2));
};


/**
 * @param {?proto.agent_kit.GetAssistantAction|undefined} value
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
*/
proto.agent_kit.AssistantActionRequest.prototype.setGet = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.agent_kit.AssistantActionRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
 */
proto.agent_kit.AssistantActionRequest.prototype.clearGet = function() {
  return this.setGet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AssistantActionRequest.prototype.hasGet = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ExecuteAssistantAction execute = 3;
 * @return {?proto.agent_kit.ExecuteAssistantAction}
 */
proto.agent_kit.AssistantActionRequest.prototype.getExecute = function() {
  return /** @type{?proto.agent_kit.ExecuteAssistantAction} */ (
    jspb.Message.getWrapperField(this, proto.agent_kit.ExecuteAssistantAction, 3));
};


/**
 * @param {?proto.agent_kit.ExecuteAssistantAction|undefined} value
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
*/
proto.agent_kit.AssistantActionRequest.prototype.setExecute = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.agent_kit.AssistantActionRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AssistantActionRequest} returns this
 */
proto.agent_kit.AssistantActionRequest.prototype.clearExecute = function() {
  return this.setExecute(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AssistantActionRequest.prototype.hasExecute = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.AssistantActionResult.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.AssistantActionResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.AssistantActionResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    data: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.AssistantActionResult}
 */
proto.agent_kit.AssistantActionResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.AssistantActionResult;
  return proto.agent_kit.AssistantActionResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.AssistantActionResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.AssistantActionResult}
 */
proto.agent_kit.AssistantActionResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.AssistantActionResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.AssistantActionResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.AssistantActionResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getData();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.agent_kit.AssistantActionResult.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.agent_kit.AssistantActionResult} returns this
 */
proto.agent_kit.AssistantActionResult.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string data = 2;
 * @return {string}
 */
proto.agent_kit.AssistantActionResult.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.agent_kit.AssistantActionResult} returns this
 */
proto.agent_kit.AssistantActionResult.prototype.setData = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.agent_kit.AssistantActionResponse.oneofGroups_ = [[10]];

/**
 * @enum {number}
 */
proto.agent_kit.AssistantActionResponse.DataCase = {
  DATA_NOT_SET: 0,
  RESULT: 10
};

/**
 * @return {proto.agent_kit.AssistantActionResponse.DataCase}
 */
proto.agent_kit.AssistantActionResponse.prototype.getDataCase = function() {
  return /** @type {proto.agent_kit.AssistantActionResponse.DataCase} */(jspb.Message.computeOneofCase(this, proto.agent_kit.AssistantActionResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.AssistantActionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.AssistantActionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.AssistantActionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    error: (f = msg.getError()) && common_pb.Error.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.agent_kit.AssistantActionResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.AssistantActionResponse}
 */
proto.agent_kit.AssistantActionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.AssistantActionResponse;
  return proto.agent_kit.AssistantActionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.AssistantActionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.AssistantActionResponse}
 */
proto.agent_kit.AssistantActionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 4:
      var value = new common_pb.Error;
      reader.readMessage(value,common_pb.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 10:
      var value = new proto.agent_kit.AssistantActionResult;
      reader.readMessage(value,proto.agent_kit.AssistantActionResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.AssistantActionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.AssistantActionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.AssistantActionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AssistantActionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.agent_kit.AssistantActionResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 code = 1;
 * @return {number}
 */
proto.agent_kit.AssistantActionResponse.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
 */
proto.agent_kit.AssistantActionResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.agent_kit.AssistantActionResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
 */
proto.agent_kit.AssistantActionResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional Error error = 4;
 * @return {?proto.Error}
 */
proto.agent_kit.AssistantActionResponse.prototype.getError = function() {
  return /** @type{?proto.Error} */ (
    jspb.Message.getWrapperField(this, common_pb.Error, 4));
};


/**
 * @param {?proto.Error|undefined} value
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
*/
proto.agent_kit.AssistantActionResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
 */
proto.agent_kit.AssistantActionResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AssistantActionResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional AssistantActionResult result = 10;
 * @return {?proto.agent_kit.AssistantActionResult}
 */
proto.agent_kit.AssistantActionResponse.prototype.getResult = function() {
  return /** @type{?proto.agent_kit.AssistantActionResult} */ (
    jspb.Message.getWrapperField(this, proto.agent_kit.AssistantActionResult, 10));
};


/**
 * @param {?proto.agent_kit.AssistantActionResult|undefined} value
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
*/
proto.agent_kit.AssistantActionResponse.prototype.setResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.agent_kit.AssistantActionResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AssistantActionResponse} returns this
 */
proto.agent_kit.AssistantActionResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AssistantActionResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.agent_kit.AgentTalkRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.agent_kit.AgentTalkRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  CONFIGURATION: 2,
  MESSAGE: 3
};

/**
 * @return {proto.agent_kit.AgentTalkRequest.RequestCase}
 */
proto.agent_kit.AgentTalkRequest.prototype.getRequestCase = function() {
  return /** @type {proto.agent_kit.AgentTalkRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.agent_kit.AgentTalkRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.AgentTalkRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.AgentTalkRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.AgentTalkRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AgentTalkRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    configuration: (f = msg.getConfiguration()) && common_pb.AssistantConversationConfiguration.toObject(includeInstance, f),
    message: (f = msg.getMessage()) && common_pb.AssistantConversationUserMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.AgentTalkRequest}
 */
proto.agent_kit.AgentTalkRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.AgentTalkRequest;
  return proto.agent_kit.AgentTalkRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.AgentTalkRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.AgentTalkRequest}
 */
proto.agent_kit.AgentTalkRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new common_pb.AssistantConversationConfiguration;
      reader.readMessage(value,common_pb.AssistantConversationConfiguration.deserializeBinaryFromReader);
      msg.setConfiguration(value);
      break;
    case 3:
      var value = new common_pb.AssistantConversationUserMessage;
      reader.readMessage(value,common_pb.AssistantConversationUserMessage.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.AgentTalkRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.AgentTalkRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.AgentTalkRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AgentTalkRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfiguration();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.AssistantConversationConfiguration.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_pb.AssistantConversationUserMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional AssistantConversationConfiguration configuration = 2;
 * @return {?proto.AssistantConversationConfiguration}
 */
proto.agent_kit.AgentTalkRequest.prototype.getConfiguration = function() {
  return /** @type{?proto.AssistantConversationConfiguration} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationConfiguration, 2));
};


/**
 * @param {?proto.AssistantConversationConfiguration|undefined} value
 * @return {!proto.agent_kit.AgentTalkRequest} returns this
*/
proto.agent_kit.AgentTalkRequest.prototype.setConfiguration = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.agent_kit.AgentTalkRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkRequest} returns this
 */
proto.agent_kit.AgentTalkRequest.prototype.clearConfiguration = function() {
  return this.setConfiguration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkRequest.prototype.hasConfiguration = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AssistantConversationUserMessage message = 3;
 * @return {?proto.AssistantConversationUserMessage}
 */
proto.agent_kit.AgentTalkRequest.prototype.getMessage = function() {
  return /** @type{?proto.AssistantConversationUserMessage} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationUserMessage, 3));
};


/**
 * @param {?proto.AssistantConversationUserMessage|undefined} value
 * @return {!proto.agent_kit.AgentTalkRequest} returns this
*/
proto.agent_kit.AgentTalkRequest.prototype.setMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.agent_kit.AgentTalkRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkRequest} returns this
 */
proto.agent_kit.AgentTalkRequest.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkRequest.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.agent_kit.AgentTalkResponse.oneofGroups_ = [[10,12,14,15,20,21]];

/**
 * @enum {number}
 */
proto.agent_kit.AgentTalkResponse.DataCase = {
  DATA_NOT_SET: 0,
  INTERRUPTION: 10,
  ASSISTANT: 12,
  DISCONNECTACTION: 14,
  HOLDACTION: 15,
  ASSISTANTTRANSFERACTION: 20,
  PHONECALLTRANSFERACTION: 21
};

/**
 * @return {proto.agent_kit.AgentTalkResponse.DataCase}
 */
proto.agent_kit.AgentTalkResponse.prototype.getDataCase = function() {
  return /** @type {proto.agent_kit.AgentTalkResponse.DataCase} */(jspb.Message.computeOneofCase(this, proto.agent_kit.AgentTalkResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agent_kit.AgentTalkResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.agent_kit.AgentTalkResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agent_kit.AgentTalkResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AgentTalkResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    error: (f = msg.getError()) && common_pb.Error.toObject(includeInstance, f),
    interruption: (f = msg.getInterruption()) && common_pb.AssistantConversationInterruption.toObject(includeInstance, f),
    assistant: (f = msg.getAssistant()) && common_pb.AssistantConversationAssistantMessage.toObject(includeInstance, f),
    disconnectaction: (f = msg.getDisconnectaction()) && common_pb.AssistantConversationDisconnectAction.toObject(includeInstance, f),
    holdaction: (f = msg.getHoldaction()) && common_pb.AssistantConverstationHoldAction.toObject(includeInstance, f),
    assistanttransferaction: (f = msg.getAssistanttransferaction()) && common_pb.AssistantConversationAssistantTransferAction.toObject(includeInstance, f),
    phonecalltransferaction: (f = msg.getPhonecalltransferaction()) && common_pb.AssistantConversationPhoneCallTransferAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agent_kit.AgentTalkResponse}
 */
proto.agent_kit.AgentTalkResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agent_kit.AgentTalkResponse;
  return proto.agent_kit.AgentTalkResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agent_kit.AgentTalkResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agent_kit.AgentTalkResponse}
 */
proto.agent_kit.AgentTalkResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 4:
      var value = new common_pb.Error;
      reader.readMessage(value,common_pb.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 10:
      var value = new common_pb.AssistantConversationInterruption;
      reader.readMessage(value,common_pb.AssistantConversationInterruption.deserializeBinaryFromReader);
      msg.setInterruption(value);
      break;
    case 12:
      var value = new common_pb.AssistantConversationAssistantMessage;
      reader.readMessage(value,common_pb.AssistantConversationAssistantMessage.deserializeBinaryFromReader);
      msg.setAssistant(value);
      break;
    case 14:
      var value = new common_pb.AssistantConversationDisconnectAction;
      reader.readMessage(value,common_pb.AssistantConversationDisconnectAction.deserializeBinaryFromReader);
      msg.setDisconnectaction(value);
      break;
    case 15:
      var value = new common_pb.AssistantConverstationHoldAction;
      reader.readMessage(value,common_pb.AssistantConverstationHoldAction.deserializeBinaryFromReader);
      msg.setHoldaction(value);
      break;
    case 20:
      var value = new common_pb.AssistantConversationAssistantTransferAction;
      reader.readMessage(value,common_pb.AssistantConversationAssistantTransferAction.deserializeBinaryFromReader);
      msg.setAssistanttransferaction(value);
      break;
    case 21:
      var value = new common_pb.AssistantConversationPhoneCallTransferAction;
      reader.readMessage(value,common_pb.AssistantConversationPhoneCallTransferAction.deserializeBinaryFromReader);
      msg.setPhonecalltransferaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agent_kit.AgentTalkResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agent_kit.AgentTalkResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agent_kit.AgentTalkResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agent_kit.AgentTalkResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getInterruption();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      common_pb.AssistantConversationInterruption.serializeBinaryToWriter
    );
  }
  f = message.getAssistant();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      common_pb.AssistantConversationAssistantMessage.serializeBinaryToWriter
    );
  }
  f = message.getDisconnectaction();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      common_pb.AssistantConversationDisconnectAction.serializeBinaryToWriter
    );
  }
  f = message.getHoldaction();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      common_pb.AssistantConverstationHoldAction.serializeBinaryToWriter
    );
  }
  f = message.getAssistanttransferaction();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      common_pb.AssistantConversationAssistantTransferAction.serializeBinaryToWriter
    );
  }
  f = message.getPhonecalltransferaction();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      common_pb.AssistantConversationPhoneCallTransferAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 code = 1;
 * @return {number}
 */
proto.agent_kit.AgentTalkResponse.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional Error error = 4;
 * @return {?proto.Error}
 */
proto.agent_kit.AgentTalkResponse.prototype.getError = function() {
  return /** @type{?proto.Error} */ (
    jspb.Message.getWrapperField(this, common_pb.Error, 4));
};


/**
 * @param {?proto.Error|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional AssistantConversationInterruption interruption = 10;
 * @return {?proto.AssistantConversationInterruption}
 */
proto.agent_kit.AgentTalkResponse.prototype.getInterruption = function() {
  return /** @type{?proto.AssistantConversationInterruption} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationInterruption, 10));
};


/**
 * @param {?proto.AssistantConversationInterruption|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setInterruption = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearInterruption = function() {
  return this.setInterruption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasInterruption = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional AssistantConversationAssistantMessage assistant = 12;
 * @return {?proto.AssistantConversationAssistantMessage}
 */
proto.agent_kit.AgentTalkResponse.prototype.getAssistant = function() {
  return /** @type{?proto.AssistantConversationAssistantMessage} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationAssistantMessage, 12));
};


/**
 * @param {?proto.AssistantConversationAssistantMessage|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setAssistant = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearAssistant = function() {
  return this.setAssistant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasAssistant = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional AssistantConversationDisconnectAction disconnectAction = 14;
 * @return {?proto.AssistantConversationDisconnectAction}
 */
proto.agent_kit.AgentTalkResponse.prototype.getDisconnectaction = function() {
  return /** @type{?proto.AssistantConversationDisconnectAction} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationDisconnectAction, 14));
};


/**
 * @param {?proto.AssistantConversationDisconnectAction|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setDisconnectaction = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearDisconnectaction = function() {
  return this.setDisconnectaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasDisconnectaction = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional AssistantConverstationHoldAction holdAction = 15;
 * @return {?proto.AssistantConverstationHoldAction}
 */
proto.agent_kit.AgentTalkResponse.prototype.getHoldaction = function() {
  return /** @type{?proto.AssistantConverstationHoldAction} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConverstationHoldAction, 15));
};


/**
 * @param {?proto.AssistantConverstationHoldAction|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setHoldaction = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearHoldaction = function() {
  return this.setHoldaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasHoldaction = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional AssistantConversationAssistantTransferAction assistantTransferAction = 20;
 * @return {?proto.AssistantConversationAssistantTransferAction}
 */
proto.agent_kit.AgentTalkResponse.prototype.getAssistanttransferaction = function() {
  return /** @type{?proto.AssistantConversationAssistantTransferAction} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationAssistantTransferAction, 20));
};


/**
 * @param {?proto.AssistantConversationAssistantTransferAction|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setAssistanttransferaction = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearAssistanttransferaction = function() {
  return this.setAssistanttransferaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasAssistanttransferaction = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional AssistantConversationPhoneCallTransferAction phoneCallTransferAction = 21;
 * @return {?proto.AssistantConversationPhoneCallTransferAction}
 */
proto.agent_kit.AgentTalkResponse.prototype.getPhonecalltransferaction = function() {
  return /** @type{?proto.AssistantConversationPhoneCallTransferAction} */ (
    jspb.Message.getWrapperField(this, common_pb.AssistantConversationPhoneCallTransferAction, 21));
};


/**
 * @param {?proto.AssistantConversationPhoneCallTransferAction|undefined} value
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
*/
proto.agent_kit.AgentTalkResponse.prototype.setPhonecalltransferaction = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.agent_kit.AgentTalkResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agent_kit.AgentTalkResponse} returns this
 */
proto.agent_kit.AgentTalkResponse.prototype.clearPhonecalltransferaction = function() {
  return this.setPhonecalltransferaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agent_kit.AgentTalkResponse.prototype.hasPhonecalltransferaction = function() {
  return jspb.Message.getField(this, 21) != null;
};


goog.object.extend(exports, proto.agent_kit);
